# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('max_pullups', models.IntegerField()),
                ('total_pullups', models.IntegerField()),
                ('daily_total_pullups', models.IntegerField(blank=True, null=True)),
                ('monthly_total_pullups', models.IntegerField()),
            ],
        ),
    ]
